In [1]:
import numpy as np
import cv2

print(cv2.__version__)

4.1.0


In [ ]:
#Get the image 
img = cv2.imread('numbers.jpg')

print(img)

In [2]:
cv2.imshow('Working', img)

[[[113 123 110]
  [121 131 118]
  [125 135 122]
  ...
  [126 132 127]
  [125 130 128]
  [123 128 126]]

 [[115 125 112]
  [120 130 117]
  [124 134 121]
  ...
  [125 131 126]
  [126 131 129]
  [124 129 127]]

 [[117 127 114]
  [120 130 117]
  [122 132 119]
  ...
  [123 130 125]
  [125 130 128]
  [124 129 127]]

 ...

 [[ 92 102  89]
  [ 93 103  90]
  [ 93 103  90]
  ...
  [ 99 107 100]
  [100 107 102]
  [100 110 104]]

 [[ 95 104  91]
  [ 94 103  90]
  [ 94 103  90]
  ...
  [ 98 107  97]
  [100 108 101]
  [100 111 103]]

 [[ 96 105  92]
  [ 95 104  91]
  [ 94 103  90]
  ...
  [ 98 107  97]
  [100 108 101]
  [100 111 103]]]


#converts img to gray and blurs
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (5, 5), 0)    

#thresholds the image
im_th = cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY,11,2)

#Finds the contours 
contours, hierarchy = cv2.findContours(im_th, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#Clean the contour noise
min_area = 300     #threshold area
max_area = 1000
contours = [cnt for cnt in contours if min_area < cv2.contourArea(cnt) and max_area > cv2.contourArea(cnt)]

#draws the contours 
    cv2.drawContours(gray, contours, -1, (0,255,0), 3)

#Draw the rect
## Get rectangles contains each contour
rects = [cv2.boundingRect(ctr) for ctr in contours]
    
    ##Draw
for rect in rects:
    # Draw the rectangles
    cv2.rectangle(gray, (rect[0], rect[1]), (rect[0] + rect[2], rect[1] + rect[3]), (0, 255, 0), 3) 
        
        
       
    # Make the rectangular region around the digit
    x = int(rect[0])
    y = int(rect[1])
    w = int(rect[2])
    h = int(rect[3])
        
    x2 = int(1.2*(x+w))
    y2 = int(1.2*(y+h))
    roi = gray[x:x2, y:y2]


#resize the region of interest to 28x28


#feed it to the NN


#Write the output of NN above the ROI


# Display the resulting frame

cv2.imshow('frame', gray)

if cv2.waitKey(1) & 0xFF == ord('q'):
    break



  # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.GaussianBlur(gray, (5, 5), 0)
    
    # Threshold the image
    ret, im_th = cv2.threshold(gray, 90, 255, cv2.THRESH_BINARY_INV)
    
    # Find contours in the image
    ctrs, hier = cv2.findContours(im_th.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # Get rectangles contains each contour
    rects = [cv2.boundingRect(ctr) for ctr in ctrs]

    
    for rect in rects:
        # Draw the rectangles
        cv2.rectangle(gray, (rect[0], rect[1]), (rect[0] + rect[2], rect[1] + rect[3]), (0, 255, 0), 3) 
        # Make the rectangular region around the digit
        leng = int(rect[3] * 1.6)
        pt1 = int(rect[1] + rect[3] // 2 - leng // 2)
        pt2 = int(rect[0] + rect[2] // 2 - leng // 2)
        roi = im_th[pt1:pt1+leng, pt2:pt2+leng]
        # Resize the image
        #roi = cv2.resize(roi, (28, 28), interpolation=cv2.INTER_AREA)
        #roi = cv2.dilate(roi, (3, 3))

roi

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
